### ISSUE TITLE
How to custom predictors for Direct multi-step forecast

### ISSUE THREAD

**Issue by xlsi** [skforecast/skforecast#496]
Hi all,

I found we can add custom predictors for ForecasterAutoreg, but what if I need to custom predictors for ForecasterAutoregDirect?

Thanks!

**Comment by JavierEscobarOrtiz** [comment]
Hello @xlsi 

Currently, there is no implementation to apply custom predictors with a direct multi-step forecasting strategy.

We have this feature in our backlog, but would be happy if someone would like to contribute to skforecast and develop it.

We really appreciate your feedback on what the community is looking for.

Best,

Javier

**Comment by joshuargst** [comment]
I think this would be extremely useful. Its particularly of interest to me when I for example dont want the response variable to be used as lagged predictors and only the exogenous variables.

**Comment by JavierEscobarOrtiz** [comment]
Hi @joshuargst 

In skforecast 0.14.0, ForecasterDirect (ForecasterAutoregDirect renamed) now allows the creation of [window and custom features](https://skforecast.org/0.14.0/user_guides/window-features-and-custom-features)

Hope it helps!
