### ISSUE TITLE
Feature request: Custom predictors for multivariate forecasting

### ISSUE THREAD

**Issue by KishManani** [skforecast/skforecast#644]
[`ForecasterMultiVariate`](https://skforecast.org/0.11.0/api/forecastermultivariate) appears to only allow lag features to be created from the target time series. It would be helpful to be able to create rolling statistics from the target (aka window features) as well (like `ForecasterMultiSeriesCustom`).

**Comment by gkrampah** [comment]
This is a feature I would like to see implemented as well

**Comment by JavierEscobarOrtiz** [comment]
Hi @KishManani, @gkrampah 

In skforecast 0.14.0, `ForecasterDirectMultiVariate` now allows the creation of [window and custom features](https://skforecast.org/0.14.0/user_guides/window-features-and-custom-features)

Hope it helps!
