### ISSUE TITLE
Forecaster with Deep Learning - GPU

### ISSUE THREAD

**Issue by AVPokrovsky** [skforecast/skforecast#726]
Hi, I run on google colab. It seems GPU does not work despite it is active in notebook settings. What can be wrong?

**Comment by FernandoCarazoMelo** [comment]
Hi @AVPokrovsky ,

Thanks for your comment.

The `ForecasterRNN` fits a Keras/TensorFlow model under the hood. Therefore, there are no reasons why Colab is not using the GPU apart from those specific to Keras/TensorFlow. I recommend you:

1. Check the GPU availability:
   ```python
   print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
   ```

2. Make sure that you run the code with the GPU:
   ```python
   with tf.device('/GPU:0'):
       # ...
   ```

Let me know if this solves your issue and if you need any further assistance!

**Comment by AVPokrovsky** [comment]
Hi, like this?

with tf.device('/GPU:0'):
      forecaster.fit(series=data_m)

**Comment by FernandoCarazoMelo** [comment]
I would recommend checking out the official TF & Colab GPU documentation:

- https://www.tensorflow.org/guide/gpu
- https://colab.research.google.com/notebooks/gpu.ipynb

**Comment by AVPokrovsky** [comment]
Hi, 
I put in code tf.debugging.set_log_device_placement(True) to show GPU usage. Run the same program on colab and locally on my computer with CPU only. I see in the log that as expected GPU0 is used on colab and CPU0 locally. But it is strange that CPU run the program quicker than GPU (412.60607266426086 seconds vs 449.97930932044983 seconds). In the past I run on colab another program that used tensowflow and keras directly without skforecast. And effect from GPU was very big (ten times ore more). Listings are
[2024.docx](https://github.com/user-attachments/files/15909179/2024.docx)
 attached.

**Comment by AVPokrovsky** [comment]
the test from colab shows for me:

https://colab.research.google.com/notebooks/gpu.ipynb

Time (s) to convolve 32x7x7x3 filter over random 100x100x100x3 images (batch x height x width x channel). Sum of ten runs.
CPU (s):
6.06291970800001
GPU (s):
0.12086969300000305
GPU speedup over CPU: 50x

**Comment by FernandoCarazoMelo** [comment]
Thanks for the benchmark. I'll take a look at it.

**Comment by AVPokrovsky** [comment]
[LSTM.txt](https://github.com/user-attachments/files/15918012/LSTM.txt)
It will takes time to explain how to run my code. But I see the same effect on your code example. I just add time measure in the code (attached). First I run it on colab with GPU  - Execution time: 132.4332287311554 seconds. After that I switched off GPU in notebook settings and run again - Execution time: 119.97605085372925 seconds. CPU works faster.

**Comment by JoaquinAmatRodrigo** [comment]
Hi @FernandoCarazoMelo 
Are you still working on a guideline on how to use GPU and ForecasterRNN?

**Comment by FernandoCarazoMelo** [comment]
Yes. I'll test it, hopefully for the next release.

**Comment by FernandoCarazoMelo** [comment]
Hi @AVPokrovsky,

Apologies for the delay in responding to this issue. The GPU works with the current implementation of skforecast.

The problem you are likely encountering is that for small batches, the GPU does not perform as efficiently. The GPU benefits from larger batch sizes to process data in parallel. If you are using a very small batch size, the performance of the GPU will be similar to that of the CPU.

If you run the batch size used in the example, the performance might be similar. However, if you train a more complex network with a larger batch size, you will see a significant difference. For example, in my case, training time went from 1m 20s (CPU) to 6s! (GPU) using an NVIDIA T4 GPU. See the screenshot below.

In summary, you don't need to do anything special to run on the GPU, as long as it's properly configured and detected using `torch.cuda.is_available()`.

Let me know if you have any other issues.

Cheers,
Fernando

@JoaquinAmatRodrigo we can close this issue.

---

Code:
```
# Create model
# ==============================================================================
series = ["o3"]  # Series used as predictors
levels = ["o3"]  # Target series to predict
lags = 32  # Past time steps to be used to predict the target
steps = 1  # Future time steps to be predicted

data = air_quality[series].copy()
data_train = air_quality_train[series].copy()
data_val = air_quality_val[series].copy()
data_test = air_quality_test[series].copy()

model = create_and_compile_model(
    series=data_train,
    levels=levels, 
    lags=lags,
    steps=steps,
    recurrent_layer="LSTM",
    recurrent_units=[100,100,100,100],
    dense_units=[64,32,16,8],
    optimizer=Adam(learning_rate=0.01), 
    loss=MeanSquaredError()
)
model.summary()

# Forecaster Definition
# ==============================================================================
forecaster = ForecasterRnn(
    regressor=model,
    levels=levels,
    transformer_series=MinMaxScaler(),
    fit_kwargs={
        "epochs": 3,  # Number of epochs to train the model.
        "batch_size": 2048,  # Batch size to train the model.
        "callbacks": [
            EarlyStopping(monitor="val_loss", patience=5)
        ],  # Callback to stop training when it is no longer learning.
        "series_val": data_val,  # Validation data for model training.
    },
)    

forecaster

# Fit forecaster
# ==============================================================================
forecaster.fit(data_train)
```
![image](https://github.com/user-attachments/assets/410e49cf-aeb9-4457-a363-bf03d23b31a8)
