### ISSUE TITLE
Good First Issue [Deep Learning]: Add Support for Different Activation Functions in Multi-Layer Neural Networks

### ISSUE THREAD

**Issue by FernandoCarazoMelo** [skforecast/skforecast#812]
### Issue Description:

Currently, the `create_and_compile` (ForcasterRNN) function only supports a single activation function for all layers in a multi-layer neural network. To increase flexibility, it would be beneficial to allow users to specify different activation functions for each layer when multiple layers are present. This would enable more fine-grained control over the behavior of the model.

### Feature Request:

Enhance the function to support different activation functions for each layer in the network. This should apply both to the recurrent and dense layers, allowing users to pass a list of activation functions corresponding to each layer.

### Acceptance Criteria:
- [ ] Modify the function to accept a list of activation functions for both recurrent and dense layers.
  - If a single activation function is provided, it should be applied to all layers (as in the current behavior).
  - If a list is provided, each layer should use the corresponding activation function from the list.
- [ ] Validate that the number of activation functions matches the number of layers in the network.
- [ ] Update the documentation and docstrings to explain the new functionality.
- [ ] Add unit tests to verify the behavior for both single and multiple activation functions.

### Example:

```python
# Example with different activation functions for each layer
model = create_and_compile(
    lags=10, 
    n_series=5, 
    recurrent_units=[32, 64], 
    dense_units=[64, 32], 
    optimizer="adam", 
    activation=["relu", "tanh"],  # List of activation functions
    loss="mse",
    compile_kwargs={}
)
```

In this example, the first recurrent layer would use `"relu"` and the second recurrent layer would use `"tanh"`. Similarly, for dense layers, different activation functions can be applied as specified by the list.

### Notes:
- Ensure backward compatibility: If a single activation function is passed, it should be applied to all layers (recurrent or dense), preserving the current behavior.
- If a list of activation functions is passed, ensure that it matches the number of layers for proper assignment.
- Provide clear error messages if the list of activation functions does not match the number of layers.

This feature will allow users to customize the behavior of each layer more precisely, opening up possibilities for more advanced model designs.

**Comment by JavierEscobarOrtiz** [comment]
@astrojuanlu

**Comment by pablorodriper** [comment]
Hi @FernandoCarazoMelo,

I have a question/suggestion. Instead of using a list that matches the number of layers, I would recommend using a dictionary with the layer names "recurrent_units" and "dense_units" as keys. This would allow for more granular customization for each layer.

I’m also not sure about requiring both the recurrent and dense layers to have the same number of layers.

For example:

```python
model = create_and_compile(
    ... 
    recurrent_units=[32, 64], 
    dense_units=[64, 32], 
    ... 
    activation={
        "recurrent_units": ["relu", "relu"], 
        "dense_units": ["relu", "tanh"],
    },
    ...
)
```

If this approach works for you, I can start working on this issue.

**Comment by FernandoCarazoMelo** [comment]
Hi @pablorodriper ,

Thanks for the suggestion! The idea of using a dictionary is interesting and does add flexibility, but I’d like to keep the list approach here to simplify the user interface. While a dictionary might allow more granularity, it could also make the configuration more complex for users who just want to specify a straightforward set of activations per layer.

By using a list, the activations are defined explicitly in the arguments, making it clear which activation corresponds to each layer in recurrent_units and dense_units. I’d prefer for the function to accept a list of activations that matches the number of layers, keeping it simple and easy to understand for most users.

Would it be okay if we proceed with this implementation?

Thanks for your input and support on the project.
