### ISSUE TITLE
Fixed set_output pandas when using PowerTransformer as transformer_y and transformer_series

### ISSUE THREAD

**Issue by JoaquinAmatRodrigo** [skforecast/skforecast#871]
### Discussed in https://github.com/skforecast/skforecast/discussions/858

<div type='discussions-op-text'>

<sup>Originally posted by **jrodenbergrheem** November 25, 2024</sup>
Is there an integration for Boxcox within Skforecast??? 

I was hoping you all had a trick to integrate sktime's transformers (BoxCox Guerrero). I have tried utilzing it but it doesn't seem compatible. 

I also tried sklearns "PowerTransformer" and it seems to be attempting to call .ravel() on a dataframe causing an error. 

Can post a reproducible example but I am sure this has been done before,

Thanks! </div>

**Comment by JavierEscobarOrtiz** [comment]
Hi @jrodenbergrheem

`transform_numpy` function in the `utils` module has been fixed in the branch skforecast 0.15.0 to work when transformers output in `scikit-learn` is `set_output(transform='pandas')`.
