### ISSUE TITLE
ForecasterDirectMultiVariate converts everything to "category" and fails with Xgboost/Lightgbm

### ISSUE THREAD

**Issue by Arnechos** [skforecast/skforecast#880]
Hi guys, so far I love the library however when trying to use Xgboost/Lightgbm  with ForecasterDirectMultiVariate I get an error related to data type (with XGBoost - `ValueError: DataFrame.dtypes for data must be int, float, bool or category.`)

I've seen this issue mentioning it before - https://github.com/skforecast/skforecast/issues/781 but I've checked that DirectMultiVariate doesn't include the id column but instead for some reason all of the columns from pandas df are being cast to "category" dtype from numericals (even the lag ones created by library `Invalid columns: lead0_lag_1: object, lead0_lag_7: object, lead0_lag_14: object`)

I've managed to run only HistGradientBoostingRegressor with this issue but I don't think it's correct to have everything converted to the category

**Comment by JoaquinAmatRodrigo** [comment]
Hi @Arnechos,
Thank you for using skforecast!
Could you please provide a minimal reproducible example? It will greatly help us in diagnosing and resolving the issue.

**Comment by Arnechos** [comment]
@JoaquinAmatRodrigo Turns out I've found the issue - one exog feature had dtype "UInt32", after running .astype(int) on it the error went away. There's something weird inside pandas I guess. We can close it and leave for the future generation :)
